import React, { Suspense, useEffect } from "react";
import Header from "../components/header/Header";
import { useSession } from "next-auth/react";
import ProfileCompletion from "../components/sections/ProfileCompletion";
import Head from "next/head";
import { RootState } from "../store";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";
const MainBuilder = dynamic(
  () =>
    import("../components/sections/main/MainBuilder").then(
      (mod) => mod.MainBuilder
    ),
  {
    ssr: false,
  }
);

function DashboardPage() {
  const { data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/auth/signin");
    },
  });
  const router = useRouter();
  const result = useSelector((state: RootState) => state.userDetails.value);
  return (
    <main className="w-full min-h-screen items-start justify-start flex flex-col ">
      {Object.values(result).some((value) => value !== "") && (
        <Head>
          <title>
            {result.firstName} {result.lastName} | DevList Profile
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      )}
      <Header session={session} />
      <div className="lg:grid grid-cols-12 place-items-start w-full min-h-screen">
        <ProfileCompletion />
        <MainBuilder session={session} />
        <div className="col-span-1 py-2 w-full h-full"></div>
      </div>
    </main>
  );
}

export default DashboardPage;
