import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const { data: session, status } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (status === "unauthenticated") router.push("/auth/signin");
  }, [session]);
  return (
    <div className="w-full h-screen items-center justify-center flex">
      <Head>
        <title>showcase your works in a single place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-400"> {session?.user?.email} </h1>
    </div>
  );
}
